# Generated by Django 4.2.6 on 2023-10-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restuarante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Restaurante')),
                ('horario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horario')),
                ('zona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurante',
                'db_table': 'restaurante',
                'ordering': ['-created_at'],
                'default_related_name': 'Restaurante',
            },
        ),
    ]
