# Generated by Django 4.2.6 on 2023-10-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurante',
            options={'default_related_name': 'Restaurante', 'ordering': ['-created_at'], 'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
        migrations.AlterModelTable(
            name='restaurante',
            table='restaurate',
        ),
    ]
