# Generated by Django 4.2.6 on 2023-10-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_restaurante_options_alter_restaurante_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='pais',
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizacion'),
        ),
    ]
