# Generated by Django 4.2.6 on 2023-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocliente',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
    ]
