# Generated by Django 4.2.6 on 2023-10-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('serviciocliente', '0002_serviciocliente_estado_alter_serviciocliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocliente',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoria'),
        ),
    ]
