# Generated by Django 4.2.6 on 2023-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0003_serviciocliente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocliente',
            name='comentario',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='serviciocliente',
            name='usuario',
            field=models.CharField(blank=True, choices=[('GUATEMALA', 'GUATEMALA'), ('EL SALVADOR', 'EL SALVADOR'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('COSTA RICA', 'COSTA RICA'), ('PANAMA', 'PANAMA')], default=None, max_length=50, null=True, verbose_name='Usuario'),
        ),
    ]
