# Generated by Django 4.2.6 on 2023-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0004_serviciocliente_comentario_serviciocliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciocliente',
            name='checkin',
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='usuario',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Usuario'),
        ),
    ]
