# Generated by Django 4.2.6 on 2023-10-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciocliente', '0005_remove_serviciocliente_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocliente',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='usuario',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Encargado'),
        ),
    ]
