# Generated by Django 4.2.6 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
            ],
            options={
                'verbose_name': 'Categoría de tráfico',
                'verbose_name_plural': 'Categoría de tráfico',
                'db_table': 'categoriatrafico',
                'ordering': ['-created_at'],
                'default_related_name': 'Categoría de tráfico',
            },
        ),
    ]
