# Generated by Django 4.2.6 on 2023-10-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la región')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
                'ordering': ['-created_at'],
                'default_related_name': 'Región',
            },
        ),
        migrations.CreateModel(
            name='Localizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callei', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('callf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('avenidai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('avenidaf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('zona', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('tienda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona')),
                ('horario_entrada', models.TimeField(verbose_name='Horario')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localizar.regiones', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Localizador',
                'verbose_name_plural': 'Localizador',
                'db_table': 'localizador',
                'ordering': ['-created_at'],
                'default_related_name': 'Localizador',
            },
        ),
    ]
