# Generated by Django 4.2.6 on 2023-10-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoriatrafico', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoriatrafico.categoriatrafico', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Tráfico',
                'verbose_name_plural': 'Tráfico',
                'db_table': 'trafico',
                'ordering': ['-created_at'],
                'default_related_name': 'Tráfico',
            },
        ),
    ]
