# Generated by Django 4.2.6 on 2023-10-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restuarante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Restaurante')),
                ('horario_entrada', models.TimeField(auto_now=True, verbose_name='Hora inicio')),
                ('horario_salida', models.TimeField(verbose_name='Hora fin')),
                ('zona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zona')),
                ('colonia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colonia')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripción')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
                'db_table': 'colonia',
                'ordering': ['-created_at'],
                'default_related_name': 'Colonia',
            },
        ),
    ]
