# Generated by Django 4.2.6 on 2023-10-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='horario_entrada',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora inicio'),
        ),
    ]
