# Generated by Django 4.2.6 on 2023-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonia', '0002_alter_colonia_horario_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonia',
            name='horario_entrada',
            field=models.TimeField(verbose_name='Hora inicio'),
        ),
    ]
